// <auto-generated />
using System;
using LabSysManager_Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LabSysManager_Infra.Migrations
{
    [DbContext(typeof(LabSysManagerContext))]
    partial class LabSysManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LabSysManager_Domain.Models.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Altura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataNasc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Idade")
                        .HasColumnType("bigint");

                    b.Property<string>("Mae")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint");

                    b.Property<string>("Pai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Peso")
                        .HasColumnType("bigint");

                    b.Property<string>("Rg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Signo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefoneFixo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoSanguineo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cliente");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b9feed95-8b58-4a13-8873-226499232776"),
                            Altura = "1,73",
                            Celular = "(34) 99963-1139",
                            Cep = "38183-044",
                            Cidade = "Araxá",
                            Cor = "Vermelho",
                            Cpf = "837.218.376-73",
                            DataNasc = new DateTime(2001, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "levijuanhenriquedarosa_@cmfcequipamentos.com.br",
                            Estado = "MG",
                            Idade = 18L,
                            Mae = "Giovanna Bianca Cristiane",
                            Nome = "Levi Juan Henrique da Rosa",
                            Numero = 715L,
                            Pai = "Hugo Antonio Roberto da Rosa",
                            Peso = 78L,
                            Rg = "33.171.161-8",
                            Senha = "jqAYDrlOk5",
                            Signo = "Peixes",
                            TelefoneFixo = "(34) 3670-2306",
                            TipoSanguineo = "ANegativo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
